# Current version is: __VERSION__

stages:
  - build
  - deploy
  - upload
  - refresh

include:
  - local: /src/templates/react-oss/.vars.yml
  - local: /src/templates/react-oss/.cache.yml
  - local: /src/templates/react-oss/.build.yml
  - local: /src/templates/react-oss/.deploy.yml
  - local: /src/templates/react-oss/.refresh.yml
