# Current version is: __VERSION__
# 1. 上传代码到 oss_bucket
# 2. build 命令 yarn build

stages:
  - build
  - deploy

include:
  - local: /src/templates/react-oss/.vars.yml
  - local: /src/templates/react-oss/.cache.yml
  - local: /src/templates/react-oss/multiple-bucket/.build.yml
  - local: /src/templates/react-oss/multiple-bucket/.deploy.yml
