.deploy:
  image: abcfy2/aliyun-cli:3.0.121
  stage: deploy
  extends:
    - .build-before-scripts
  script:
    - set -e
    - cd $FRONTEND_PATH_BUILD
    - aliyun oss sync . oss://$BUCKET_CONTEXT/$BUCKET_SUB_CONTEXT --force --delete

deploy-beta:
  extends: .deploy
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /__@beta__/

deploy-staging:
  extends: .deploy
  environment:
    name: staging
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /__@staging__/

deploy-sandbox:
  extends: .deploy
  environment:
    name: sandbox
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /__@sandbox__/

deploy-production:
  when: manual
  extends: .deploy
  environment:
    name: production
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /__@production__/