.deploy: &DEPLOY
  extends:
    - .global-cache-only2read
  stage: deploy
  image: registry.git.saybot.net/ops/k8s-deploy:0.5.1
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://$FRONTEND_HOSTS$FRONTEND_PATH_PUBLIC
  variables: &DEPLOY_VARIABLES
    IMAGE_REPOSITORY: $ALIYUN_CI_REGISTRY_IMAGE/frontend/$FRONTEND_PROJECT_NAME/$CI_COMMIT_REF_NAME
    IMAGE_TAG: $CI_COMMIT_SHA
    IMAGE_CREDENTIALS_USERNAME: $DEPLOY_TOKEN_USERNAME
    IMAGE_CREDENTIALS_PASSWORD: $DEPLOY_TOKEN_PASSWORD
    INGRESS_HOSTS: "[$FRONTEND_HOSTS]"
    INGRESS_PATH: $FRONTEND_PATH_PUBLIC
    INGRESS_HTTPS: "false"
    INGRESS_CLASS: nginx
    RELEASE_NAME: ${FRONTEND_PROJECT_NAME}-${CI_ENVIRONMENT_NAME}-ali
  script:
    - set -x # helm repo add alo7 https://alo7-charts.s3.cn-northwest-1.amazonaws.com.cn
    - printenv
    - curl $KUBE_URL -k
    - ls -lah node_modules/@jswork/frontend-ci/
    - echo "envsubt < $FRONTEND_CI_DIR/ci/.helm-values.yaml.tmpl | helm --tiller-namespace $KUBE_NAMESPACE upgrade --install --wait --namespace=$KUBE_NAMESPACE -f - $RELEASE_NAME $FRONTEND_CI_DIR/ci/general-frontend"
    - envsubst < $FRONTEND_CI_DIR/ci/.helm-values.yaml.tmpl | helm --tiller-namespace $KUBE_NAMESPACE upgrade --install --wait --namespace=$KUBE_NAMESPACE -f - $RELEASE_NAME $FRONTEND_CI_DIR/ci/general-frontend

deploy:master:
  <<: *DEPLOY
  when: manual
  variables:
    <<: *DEPLOY_VARIABLES
    INGRESS_CLASS: "public-nginx"
  extends:
    - .vars-master
    - .global-cache-only2read
  only:
    - master
    - main

deploy:develop:
  <<: *DEPLOY
  extends:
    - .vars-develop
    - .global-cache-only2read
  only:
    - develop
    - dev

deploy:beta:
  <<: *DEPLOY
  extends:
    - .vars-beta
    - .global-cache-only2read
  only:
    - beta

deploy:staging:
  <<: *DEPLOY
  extends:
    - .vars-staging
    - .global-cache-only2read
  only:
    - staging
